import type { Metadata } from "next";
import { Kanit,Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const kanit = Kanit({
  subsets:["thai","latin"],
  weight:["400","500","600","700"]
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ToothToday",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script 
          src="https://kit.fontawesome.com/KIT_CODE.js" 
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </head>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${kanit.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
